import assert from "node:assert/strict";
await import("./yk-agent-identity.js");
const id = globalThis.ykAgentIdentity;

assert.equal(id.display("Arquitecto", "CursorCloud"), "ArquitectoCursorCloud");
assert.equal(id.display("Arquitecto", "cursor cloud"), "ArquitectoCursorCloud");
assert.equal(id.display("architect", "cursor"), "ArquitectoCursorCloud");
assert.equal(id.display("elarquitecto", "architectcloud"), "ArquitectoCursorCloud");
assert.equal(id.suffix("CursorCloud"), "CursorCloud");
assert.equal(id.suffix("cursor-cloud"), "CursorCloud");
assert.equal(id.parse("ArquitectoCursorCloud").persona, "Arquitecto");
assert.equal(id.parse("ArquitectoCursorCloud").suffix, "CursorCloud");
assert.equal(id.display("Arquitecto", ""), "ArquitectoSINMAQ");
assert.equal(id.display("Smith", "MacMini"), "SmithMacMini");
assert.equal(id.display("SmithMini", ""), "SmithMacMini");
assert.equal(id.parse("elon musk").persona, "Musk");
assert.equal(id.parse("elon").persona, "elon");
assert.equal(id.parse("el Merovingio").persona, "Merovingio");
assert.equal(id.parse("MerovingioGrokBotBox").persona, "Merovingio");
assert.equal(id.display("Musk", "GrokBot"), "MuskGrokBot");
console.log("agent-identity CursorCloud: ok");
